// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type runqlatHistKey struct {
	_        structs.HostLayout
	CgroupId uint64
	Bucket   uint32
	_        [4]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	runqlatMapRunbTstmp    = "runb_tstmp"
	runqlatMapRunqHist     = "runq_hist"
	runqlatProgAddToMap    = "add_to_map"
	runqlatProgAddToMapNew = "add_to_map_new"
	runqlatProgFillHist    = "fill_hist"
)

// loadRunqlat returns the embedded CollectionSpec for runqlat.
func loadRunqlat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RunqlatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load runqlat: %w", err)
	}

	return spec, err
}

// loadRunqlatObjects loads runqlat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*runqlatObjects
//	*runqlatPrograms
//	*runqlatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRunqlatObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadRunqlat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// runqlatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type runqlatSpecs struct {
	runqlatProgramSpecs
	runqlatMapSpecs
	runqlatVariableSpecs
}

// runqlatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type runqlatProgramSpecs struct {
	AddToMap    *ebpf.ProgramSpec `ebpf:"add_to_map"`
	AddToMapNew *ebpf.ProgramSpec `ebpf:"add_to_map_new"`
	FillHist    *ebpf.ProgramSpec `ebpf:"fill_hist"`
}

// runqlatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type runqlatMapSpecs struct {
	RunbTstmp *ebpf.MapSpec `ebpf:"runb_tstmp"`
	RunqHist  *ebpf.MapSpec `ebpf:"runq_hist"`
}

// runqlatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type runqlatVariableSpecs struct {
}

// runqlatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRunqlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type runqlatObjects struct {
	runqlatPrograms
	runqlatMaps
	runqlatVariables
}

func (o *runqlatObjects) Close() error {
	return _RunqlatClose(
		&o.runqlatPrograms,
		&o.runqlatMaps,
	)
}

// runqlatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRunqlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type runqlatMaps struct {
	RunbTstmp *ebpf.Map `ebpf:"runb_tstmp"`
	RunqHist  *ebpf.Map `ebpf:"runq_hist"`
}

func (m *runqlatMaps) Close() error {
	return _RunqlatClose(
		m.RunbTstmp,
		m.RunqHist,
	)
}

// runqlatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRunqlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type runqlatVariables struct {
}

// runqlatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRunqlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type runqlatPrograms struct {
	AddToMap    *ebpf.Program `ebpf:"add_to_map"`
	AddToMapNew *ebpf.Program `ebpf:"add_to_map_new"`
	FillHist    *ebpf.Program `ebpf:"fill_hist"`
}

func (p *runqlatPrograms) Close() error {
	return _RunqlatClose(
		p.AddToMap,
		p.AddToMapNew,
		p.FillHist,
	)
}

func _RunqlatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed runqlat_bpfel.o
var _RunqlatBytes []byte
