name: golangci-lint

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.6'

      - name: Install clang
        run: sudo apt-get update && sudo apt-get install -y clang llvm

      - name: Generate eBPF bindings
        run: go generate ./...

      - name: test go code
        run: go test -race ./...


  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.6'
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.5.0
      
      - name: Run golangci-lint
        run: golangci-lint run ./...

